// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcnitwgsbjyryqvdgbtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhjbml0d2dzYmp5cnlxdmRnYnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTk4MjUsImV4cCI6MjA2Nzk5NTgyNX0.ek4DOfKISyafX1UNk0aGxWijQmqKfej2QOf3MglPntI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});